# Auto-generated by /home/powware/repos/edk2/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/powware/repos/uefi-rootkit
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/powware/repos/edk2/BaseTools
fi
if [ -e /home/powware/repos/edk2/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/powware/repos/edk2/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/powware/repos/edk2/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
